repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: golang
        types: [go]
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: golang
        types: [go]
        pass_filenames: false

      - id: go-test
        name: go test
        entry: go test ./...
        language: golang
        types: [go]
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy check
        entry: ./scripts/check-go-mod.sh
        language: system
        pass_filenames: false
