name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # or your preferred version

      - name: Install dependencies
        run: go mod tidy

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "Run 'gofmt -s -w .' to fix formatting issues"
            exit 1
          fi

      - name: Static analysis (go vet)
        run: go vet ./...

      - name: Run unit tests
        run: go test -v ./...

      - name: Set up Python for pre-commit
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
        # Optional: if you're missing pre-commit config, this will fail unless you have a .pre-commit-config.yaml
        continue-on-error: true
